### ISSUE TITLE
Nearest Neighbour algorithm does not test different options if weights are the same

### ISSUE THREAD

**Issue by jastaehl** [mhahsler/TSP#1]
Hi guys,

Can you let me know why if weights are the same, simply the first option is chosen and not several ones tested? I believe that would optimize the code greatly.
Thanks a lot!

Cheers
Jackie

**Comment by mhahsler** [comment]
Please be a little more specific. What function do you refer to? Please also share some code that shows where this improvement can be made.

Thanks,
Michael

**Comment by jastaehl** [comment]
Hi Michael,
Thanks for your quick reply. I am referring to function tsp_nn.
In line 53, you do the following: if(length(current) > 1L) current <- sample(current, 1), solving the issue of having equivalent choices by taking the first one.
I understand that considering all equivalent choices will lead to high number of possible combinations in some circumstances. I am facing an 8x8 matrix so I assume it would still be feasible, and by hand, I have found that it would lead at most to 4 paths to would need to be compared in the end.
An option could be that the user specifies how many tries he wants it to give? And setting an upper limit on the number of combinations. I am currently looking into it myself, and this has just been my first thought. Very happy to hear your input as well.
Thank you,
Jackie

**Comment by mhahsler** [comment]
I see. The standard algorithm implemented in TSP breaks ties randomly. Exploring all possible solution paths is only possible for very small problems. Typically, NN is just run several times to explore more solutions.  You can use the argument `repetitions` in `solve_TSP` to specify how many repetitions you would like to do. Hope this helps.
