### ISSUE TITLE
Linkern Error for some instances

### ISSUE THREAD

**Issue by jeromejarre** [mhahsler/TSP#10]
Hi,

I am using the Linkern solver without an issue for some instances. However, when I try to solve a sequence of instance my loop crashes and raises this error:

Error in tsp_linkern(x_, control = control) : 
  Problems with reading linkern's output. Is linkern properly installed?

I am using MacOS and R 3.6.1 . Thanks in advance for your help.

**Comment by mhahsler** [comment]
Hi, 

Thank you for the bug report. I have changed something with the temp files. Please install the new TSP version from GitHub and try and let me know if that solves the problem.

If that does not solve the problem, then I have a few questions:
1) Does this happen predictably every time at the same problem in the loop?
2) Can you send me an example to reproduce the problem?

-Michael
