### ISSUE TITLE
How to solve decision version of TSP using Concorde

### ISSUE THREAD

**Issue by sarwanpasha** [mhahsler/TSP#13]
Hey,

I am working with TSP using Concorde. My question is that is there a way to solve the decision version of the TSP instance? I know that TSP function give me a tour length in the output. However, is there a way to ask the tsp to return some kind of true/false in the question that whether there exists a tour of length n or not.

I am using the code for TSP, which you have given on the following URL
https://stackoverflow.com/questions/61162790/problem-in-r-studio-while-solving-traveling-salesman-problem-tsp-using-concord/61211799#61211799

**Comment by mhahsler** [comment]
Sorry for the late reply. The code only tries to find a good solution. It does not answer the decision problem unless you find a solution with a length shorter than the one you set or if Concorde runs to optimality and finds that the optimal length is longer than your threshold.
