### ISSUE TITLE
Linkern does not go beyond 1000steps

### ISSUE THREAD

**Issue by tahavarol** [mhahsler/TSP#15]
Hello,

I am using LinKernighan Heuristic along with your TSP R package. While I am trying to solve a comparably larger instances (>>1000 cities), Linkern method stops running but algorithm still uses CPU. When I stop the run, I got an error message saying that _**Error in tsp_linkern(x_, control = control) : 
  Problems with reading linkern's output. Is linkern properly installed?**_

How can I solve this problem?

**Comment by mhahsler** [comment]
You will get this if linkern crashes and does not write a complete output file. linkern might run out of memory and then the OS will kill the process. I will change the error message to make this clearer.

What does linkern say before the error message?

**Comment by tahavarol** [comment]
In fact, I stop the algorithm by hand clicking the red stop sign on RStudio. Since, the algorithm takes extremely long time. There is no prior error message. When I hit the stop sign, Linkern produces the error message provided.

**Comment by mhahsler** [comment]
That explains why no result was written and why linkern was still running in the background. You need to kill the linkern process using the task manager. 

I will make the error message clearer for the next release. You can see if linkern has parameters that yu can use to actually be able to solve your problem.
