### ISSUE TITLE
cut on multiple dummy cities

### ISSUE THREAD

**Issue by RegularnaMatrica** [mhahsler/TSP#16]
Hi,

I've noticed that when there are multiple dummy cities (boundary in example below) function cut_tour leaves out last element before first dummy city:

![image](https://user-images.githubusercontent.com/65914613/127276794-9661b133-205c-4d0c-a725-81bda03fd8df.png)

As you can see "V4" is missing.

**Comment by mhahsler** [comment]
Thank you for reporting this bug! It is now fixed in the development version on GitHub.
