### ISSUE TITLE
parallel backend

### ISSUE THREAD

**Issue by RegularnaMatrica** [mhahsler/TSP#17]
Is it possible to run `solve_TSP` sequentially even if I have registered parallel backend? I ask because I run function `f` in parallel and function `f` uses  `solve_TSP` with parameter `repetitions` > 1 (building matrix for `solve_TSP` is slower part of function `f` )

**Comment by mhahsler** [comment]
If you do not register a backend, then it should do the `foreach` loop sequentially. You can also call `foreach::registerDoSEQ()` which should achieve the same.
