### ISSUE TITLE
method = "linkern"

### ISSUE THREAD

**Issue by RegularnaMatrica** [mhahsler/TSP#19]
I need some clarifications about using `method = "linkern"` in `TSP_solve` function. It always gives me following message:

`Error in tsp_linkern(x_, control = control) : 
  Linkern has not produced a result file.
Is linkern properly installed?
Did linkern finish without an error or being interrupted?`

I have installed `concorde` and `method = "concorde"` works well. Do I need to install anything extra to use `method = "linkern"`? As a side note function `linkern_help` does not return any list of usable parameters - is this expected?

 I'm using 1.2.0.1 version of TSP package and 3.5.5 R version. Example matrix:

`structure(c(0, 183, 145, 207, 100, 152, 148, 63, 82, 100, 183, 
0, 151, 158, 132, 66, 178, 19, 319, 118, 145, 151, 0, 89, 61, 
91, 163, 235, 221, 99, 207, 158, 89, 0, 157, 100, 170, 220, 172, 
167, 100, 132, 61, 157, 0, 114, 72, 93, 27, 274, 152, 66, 91, 
100, 114, 0, 55, 246, 136, 20, 148, 178, 163, 170, 72, 55, 0, 
155, 82, 152, 63, 19, 235, 220, 93, 246, 155, 0, 111, 132, 82, 
319, 221, 172, 27, 136, 82, 111, 0, 226, 100, 118, 99, 167, 274, 
20, 152, 132, 226, 0), .Dim = c(10L, 10L))`

**Comment by mhahsler** [comment]
linkern is its own executable. You need to install it from:

https://www.math.uwaterloo.ca/tsp/concorde/downloads/downloads.htm

**Comment by RegularnaMatrica** [comment]
Thank you for feedback, its working after downloading.
