### ISSUE TITLE
Issue with R v.3.5.0

### ISSUE THREAD

**Issue by fceci** [mhahsler/TSP#2]
Thank you for sharing this package. I just want to point out that it does not work  with the newest version of R (3.5.0) in Windows 64. See CRAN results here:
[https://cran.r-project.org/web/checks/check_results_TSP.html](url)

**Comment by mhahsler** [comment]
Thanks for letting me know. This is strange. I guess the package still works under Windows, just the test for data with a single city fails. I guess I need find a Windows machine to figure out what is going on.

**Comment by mhahsler** [comment]
Win 32 issue is now resolved with TSP version 1.1-6.
