### ISSUE TITLE
Vulnerability to absence of retiring r-spatial packages

### ISSUE THREAD

**Issue by rsbivand** [mhahsler/TSP#20]
[00check.log](https://github.com/mhahsler/TSP/files/11141521/00check.log)
is a recent check log from running under `_SP_EVOLUTION_STATUS_=2` without retiring r-spatial packages (`maptools` suggested in this package) on the library path. The minimal correction is to check that the package namespaces can be loaded, and if not, do not run those parts of the examples. It would be safer in the longer term to replace retiring r-spatial packages with active r-spatial/rspatial packages (see https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html).

**Comment by mhahsler** [comment]
Hi Roger,

Thanks for letting me know. I will work on replacing the dependence on maptools.

-Michael

**Comment by mhahsler** [comment]
I have submitted a new version to CRAN that does not depend on maptools.

Regards,
-MFH

**Comment by rsbivand** [comment]
Thanks for your cooperation, this now passes check for the post-October scenario:
[00check.log](https://github.com/mhahsler/TSP/files/11159012/00check.log)
