### ISSUE TITLE
Large data - `Error: vector memory exhausted (limit reached?)` Suggestion?

### ISSUE THREAD

**Issue by amrrs** [mhahsler/TSP#6]
Hi,

I've about 200K cities / rows and I'm running into this issue always. Any suggestions what can i do?

Thanks!

**Comment by mhahsler** [comment]
A 200k x 200k distance matrix will not fit into memory. You would need 

    > 200e3*(200e3-1)/2 * 4 / 2^30
    [1] 74.50543

GB. If you have the data (coordinates of the cities) and Euclidean distance makes sense, then you can create an `ETSP` and use Concorde or Linkern to solve it. See `? ETSP`
