### ISSUE TITLE
read_TSPLIB not working correctly

### ISSUE THREAD

**Issue by ghost** [mhahsler/TSP#7]
When using your library for parsing TSP files I've got a solution that was better than the optimum solution so I've tried to find an answer to why it happened.
It turns out that `read_TSPLIB()` function isn't working correctly. At least for files with those params
EDGE_WEIGHT_TYPE: EXPLICIT
EDGE_WEIGHT_FORMAT: LOWER_DIAG_ROW 

There are 2 major problems:

1) It isn't loading the values row-wise, but column-wise.
E.g. Let's say we have 4 cities and these values in EDGE_WEIGHT_SECTION: 
0 1 0 2 3 0 4 5 6 0
By looking at TSP file format definition it should be interpreted as this matrix (since the matrix is symmetrical I will only write the lower triangular part)
**GOOD**
0
1 0
2 3 0
4 5 6 0
But instead, when using `read_TSPLIB()` we get this matrix
**WRONG**
0 
1 0
2 4 0
3 5 6 0
I've found a workaround for this (however it still isn't enough due to problem nr 2):
```
# tspMatrix can be obtained by calling as.matrix(tspInstance) where tspInstance is result of read_TSPLIB()
getCorrectedTspMatrix <- function(tspMatrix){
  weightData = tspMatrix[lower.tri(tspMatrix, diag=FALSE)]
  weightMatrix = matrix(0, nrow(tspMatrix), nrow(tspMatrix)) 
  weightMatrix[upper.tri(weightMatrix, diag=FALSE)] = weightData
  return(weightMatrix + t(weightMatrix))
}
```

2) Some data is being lost when reading from TSP file.
E.g. When using the `gr17.tsp` file (http://elib.zib.de/pub/mp-testdata/tsp/tsplib/tsp/gr17.tsp) we miss a few last values (around 8) and they are being replaced by values from the beginning of the file.
If I'm right this is because in `read_TSPLIB.R` file in line `67` you're cutting some part of the data. After commenting this line (and the preceding else if clause) the file is loaded correctly (at least as far as I'm concerned).

Please take a look at those issues since they may be affecting some people without them even noticing it.

**Comment by mhahsler** [comment]
Thank you for the detailed bug report. The read function for EDGE_WEIGHT_FORMAT: LOWER_DIAG_ROW was broken. A fixed version is now available on GitHub and will be part of the next release. Let me know if this does not resolve your problem.
